### PR TITLE
Keep up with master

### PR DESCRIPTION
**Pull request by B00M3000**

### CODE REVIEW

**Comment by JeanJPNM** [comment]
i don't understand where this is going to be merged

**Comment by B00M3000** [comment]
> i don't understand where this is going to be merged

Merging into the branch I made. Since there were updates to the master branch,

**Comment by JeanJPNM** [comment]
after spending some time thinking about it, I don't think you need to make a pull request to merge the master branch onto another , just when you will merge another branch onto master

**Comment by B00M3000** [comment]
ok

**Pull request closed without merging**
